In [1]:
import numpy as np

def np_print(nparr): print(''' type : {}
shape : {}
dimension : {}
dtype : {} data :\n {} '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [4]:
x=np.arange(5)
np_print(x)

 type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : int32 data :
 [0 1 2 3 4] 


In [8]:
#역순정렬
x[::-1]

array([4, 3, 2, 1, 0])

In [14]:
#크기에만 의존해서 정렬
a=np.random.randint(0,10,5)
np_print(a)

 type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : int32 data :
 [1 6 2 5 7] 


In [15]:
#np.sort(자료) ->원본이 바뀌지는 않음
np.sort(a)

array([1, 2, 5, 6, 7])

In [16]:
a

array([1, 6, 2, 5, 7])

In [17]:
#자료.sort()->원본에 반영
a.sort()
a

array([1, 2, 5, 6, 7])

In [18]:
b=np.random.randint(0,10,5)
np_print(b)

 type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : int32 data :
 [4 7 5 2 7] 


In [19]:
#np.argsort(자료)는 자료 내부의 아이템들을 순서대로 정렬하기 위해서 현재 인덱스 몇 번에 있는 자료를 어떤 순서로 배치해야 하는지 보여줌
np.argsort(b)

array([3, 0, 2, 1, 4], dtype=int64)

In [21]:
#0이상 1 미만의 범위에서 무작위 실수 값 가지는 3행 3열
a=np.random.random((3,3))
b=np.random.random((3,3))
np_print(a)
np_print(b)

 type : <class 'numpy.ndarray'>
shape : (3, 3)
dimension : 2
dtype : float64 data :
 [[0.57106996 0.22184305 0.30907843]
 [0.86569293 0.04870684 0.07335373]
 [0.90610945 0.9419216  0.72566121]] 
 type : <class 'numpy.ndarray'>
shape : (3, 3)
dimension : 2
dtype : float64 data :
 [[0.01479398 0.61405959 0.30860476]
 [0.13655011 0.38012566 0.11638112]
 [0.67938288 0.20423245 0.82118262]] 


##### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (행 기준 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [24]:
#기본 방향(axis=-1)
np_print(a)
np.sort(a)

 type : <class 'numpy.ndarray'>
shape : (3, 3)
dimension : 2
dtype : float64 data :
 [[0.57106996 0.22184305 0.30907843]
 [0.86569293 0.04870684 0.07335373]
 [0.90610945 0.9419216  0.72566121]] 


array([[0.22184305, 0.30907843, 0.57106996],
       [0.04870684, 0.07335373, 0.86569293],
       [0.72566121, 0.90610945, 0.9419216 ]])

##### axis = 0 (열 기준 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [25]:
#세로방향 기준 정렬
np_print(a)
np.sort(a,axis=0)

 type : <class 'numpy.ndarray'>
shape : (3, 3)
dimension : 2
dtype : float64 data :
 [[0.57106996 0.22184305 0.30907843]
 [0.86569293 0.04870684 0.07335373]
 [0.90610945 0.9419216  0.72566121]] 


array([[0.57106996, 0.04870684, 0.07335373],
       [0.86569293, 0.22184305, 0.30907843],
       [0.90610945, 0.9419216 , 0.72566121]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [27]:
#0~23까지 1씩 증가하는 값을 아이템으로
arr1 = np.arange(24)
np_print(arr1)

 type : <class 'numpy.ndarray'>
shape : (24,)
dimension : 1
dtype : int32 data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


In [29]:
#4*6의 2차원배열생성
arr2=arr1.reshape(4,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
#2차원배열 인덱싱 : 2차원배열[행인덱스,(열인덱스)]
#하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [34]:
#하나의 행에 접근 : 모든 열에 대해서 하나의 행에 접근
#반환값 : 1d array
arr2[:,0]

array([ 0,  6, 12, 18])

In [37]:
#하나의 값에 접근
arr2[2][2]
arr2[2,2]

14

In [42]:
#여러개의 행 조회
print(arr2[[0,3]])
print(arr2[[0]])
arr2

[[ 0  1  2  3  4  5]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [47]:
#여러개의 열 조회
arr2[:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [48]:
#2차원 배열 인덱싱을 통한 값 수정
#하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하는 값을 스칼라값으로 전달
#서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달
#하나의 값을 수정하는 예시
arr2[2]=9
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 9,  9,  9,  9,  9,  9],
       [18, 19, 20, 21, 22, 23]])