In [88]:
import numpy as np
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입, 객체
def np_print(arr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr))

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [7]:
# 1부터 10 미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행3열배열
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#4이상 14 미만의 범위에서 1 씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4,13).reshape(3,3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
# 10 ~ 21까지 3행 4열 형태
c = np.arange(10,22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 더하기
- 배열 + 배열
- np.add(arr1,arr2)

In [16]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#산술 연산자
a+b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [21]:
np.add(a,b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [23]:
# 구조가 다른 배열간의 산술연산시 에러발생
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기
- 배열 - 배열
- np.subtract(arr1,arr2)

In [27]:
np.subtract(a,b)
np.subtract(b,a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 나누기
- 배열 / 배열
- np.divide(arr1,arr2)

In [28]:
#산술연산자
a/b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [30]:
np.divide(a,b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

###  곱하기
- 배열 * 배열
- np.multiply(arr1,arr2)

In [31]:
#산술연산자
a*b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [32]:
np.multiply(a,b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

###  지수곱
- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [38]:
np.sqrt(2)

1.4142135623730951

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)

- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [43]:
a*b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [44]:
np.dot(a,b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

### Numpy 배열 연산

#### 2. 비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [46]:
#두 배열 요소에 대하여 값이 동일한지 비교
# 반환 : 각 요소마다의 비교결과가 배열로 포함됨
a==b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [47]:
# 두 배열 요소에 대하여 값이 다른지 비교
a!=b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
a<b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# 두 배열이 완전히 일치하는지 여부만 조회
#하나의 T/F로 반환
np.array_equal(a,b)

False

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
            - 인과관계와는 상관 X
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도, 작을 수록 오밀조밀
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique(), 갯수가 아닌 종류를 보여줌

In [52]:
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [53]:
# 합계 - 전체 기준 -> 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy 함수 : np.sum(arr)
a.sum()

45

In [54]:
np.sum(a)

45

In [55]:
# 합계 - row 가로축 기준
# 메서드. np함수의 파라미터값 : axis=1
#결과값 : (첫행합계,둘행합계,셋행합계,..)
print(c.sum(axis=1))
print(c)

[46 62 78]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [57]:
#행기준
print(np.sum(c,axis=1))

[46 62 78]


In [60]:
#1)열기준(col,세로)
print(c.sum(axis=0))
print(c)
#2)열기준(col,세로)
print(np.sum(c,axis=0))
print(c)

[42 45 48 51]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[42 45 48 51]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [61]:
# 최소값 - 전체 기준
# 배열 타입의 메서드 : arr.min()
# numpy 함수 : np.min(arr)
c.min()

10

In [62]:
np.min(c)

10

In [64]:
#(참고)파이썬 리스트 최소값
x=[1,2,3,4]
min(x)

1

In [67]:
#최소값 - 각 가로축 별 최소값 찾기(행)
print(c.min(axis=1))
print(np.min(c,axis=1))

[10 14 18]
[10 14 18]


In [69]:
#최소값 - 각 세로축 별 최소값 찾기(열)
print(c.min(axis=0))
print(np.min(c,axis=0))
c

[10 11 12 13]
[10 11 12 13]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [70]:
#최대값 전체 기준
print(c)
print(c.max())
print(np.max(c))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
21
21


In [72]:
#최대값 가로축기준
print(c.max(axis=1))
print(np.max(c,axis=1))

[13 17 21]
[13 17 21]


In [73]:
#최대값 세로축기준
print(c.max(axis=0))
print(np.max(c,axis=0))

[18 19 20 21]
[18 19 20 21]


In [76]:
# 누적합계 - 전체기준
#배열타입 : arr.cumsum()
#numpy 함수 : np.cumsum(arr)
print(c.sum())
print(c.cumsum())
print(c)

186
[ 10  21  33  46  60  75  91 108 126 145 165 186]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [80]:
#누적합계 가로축기준
print(c.cumsum(axis=1))
print(np.cumsum(c,axis=1))
c

[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [81]:
#누적합계 세로축기준
print(c.cumsum(axis=0))
print(np.cumsum(c,axis=0))
c

[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]
[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [82]:
#평균 전체 기준
print(c.mean())
print(np.mean(c))

15.5
15.5


In [83]:
#가로축 기준
print(c.mean(axis=1))
print(np.mean(c,axis=1))

[11.5 15.5 19.5]
[11.5 15.5 19.5]


In [85]:
#세로축 기준
print(c.mean(axis=0))
print(np.mean(c,axis=0))

[14. 15. 16. 17.]
[14. 15. 16. 17.]


In [94]:
#중앙값 전체기준
np.median(c)

15.5

In [96]:
#중앙 값 가로축 기준
np.median(c,axis=1)

array([11.5, 15.5, 19.5])

In [97]:
#중앙 값 세로축 기준
np.median(c,axis=0)

array([14., 15., 16., 17.])

In [101]:
#상관계수 : 두 데이터간의 상관관계(양/음의 상관관계)
#numpy : np.corrcoef(arr1,arr2) -> 두개 간에만 비교 가능
x=np.array([15,12,27,37,29])
y=np.array([1,4,2,9,7])

print(np.corrcoef(x,x))

[[1. 1.]
 [1. 1.]]


In [102]:
#서로 다른 배열 2개를 활용한 상관계수 matrix
#결과 : 대칭형 매트릭스(대각선을 경계로 상위,하위 삼각형 중 하나만 해석해도 된다.- >대칭되기 때문)
#오른쪽 아래로 향하는 대각선은 자기 자신과의 상관관계(항상1)
print(np.corrcoef(x,y))

[[1.         0.72615657]
 [0.72615657 1.        ]]


In [103]:
#numpy에서는 3개요소 불가능
#팬더스에서는 가능
#그러나 이 경우도 3개중 2개씩 조합한 모든 경우의 수를 보여주는 것이지 3자 전체의 상관관계는 존재하지 않음
z=np.array([0.3,0.5,0.6,0.8,1.3])

In [104]:
np.corrcoef(x,y,z)#오류

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [106]:
#표준편차 - 전체기준
print(a.std())
print(np.std(a))

2.581988897471611
2.581988897471611


#### (참고) 데이터가 퍼져있는 정도를 나타내는 개념

1. 편차(std/sd) : 단위에 대한 보정이 들어가 있지 않아서 상대적인 비교가 어려움
2. 변동계수(cv) : 편차/평균
    - 두 개 이상의 변수(서로 다른 단위를 사용하는 경우)에 대해 데이터가 퍼져있는 정도를 파악하는 경우

In [114]:
#고유값 - 전체 값에 적용
np.unique(c)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [117]:
#0이상 3미만의 정수 값을 가지는 3행3열
g=np.random.randint(0,4,size=(3,3))
np_print(g)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 1]
 [2 1 2]
 [1 0 2]]
    


In [121]:
np.unique(g)

array([0, 1, 2])

In [122]:
#고유값 - 가로축 기준
np.unique(g,axis=1)

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 0]])

In [123]:
#고유값 - 세로축 기준
np.unique(g,axis=0)

array([[1, 0, 2],
       [1, 2, 1],
       [2, 1, 2]])

#### 브로드캐스팅(BroadCasting)

- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
- 배열과 스칼라값 간의 연산
- 배열과 배열 간의 연산
- 브로드캐스팅 규칙 : 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐
<img src='img/broadcast.png' width='600' height='400' align='left'>

In [124]:
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
    


#### 1. 배열과 값(single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산 수행

In [125]:
#구조가 다른 배열간의 연산
# a배열에 단일 정수를 더하면 a내의 모든 요소에 단일요소를 각각 더한 더한 결과를 출력
a+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [126]:
#스칼라 -> 배열 변형
# 3행3열 구조에 모든 요소가 10
scalar_arr = np.full_like(a,10)
np_print(scalar_arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
    


#### 2. 서로 다른 구조의 배열

- 행, 열의 최대 길이를 기준으로 구조를 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성

In [128]:
#1행 4열의 구조에서 1,2,3,4를 값으로 가지는 배열 x
#4행 1열의 구조에서 1,2,3,4를 값으로 가지는 배열 y
x=np.arange(1,5).reshape(1,4)
y=np.arange(1,5).reshape(4,1)
np_print(x)
np_print(y)


    type : <class 'numpy.ndarray'>  
    shape : (1, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3 4]]
    

    type : <class 'numpy.ndarray'>  
    shape : (4, 1)  
    dimension : 2  
    dtype : int32
    data :
 [[1]
 [2]
 [3]
 [4]]
    


In [133]:
#배열 x를 동일한 값으로 4행으로 확장한 새로운 배열 생성
# 행 방향으로 배열 추가(세로길이 증가)메서드 : np.append(arr1,arr2,axis=0)
new_x=np.append(x,x,axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [135]:
new_x=np.append(new_x,new_x,axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [144]:
new_y=np.append(y,y,axis=1)
new_y

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [145]:
new_y=np.append(new_y,new_y,axis=1)
new_y

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [146]:
new_x+new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [147]:
x+y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### 벡터 연산

- 요소들에 대한 연산을 벡터 연산으로 처리하면 일반적인 for반복문으로  연산 작업을 처리하는 것 보다 월등히 뛰어난 처리 속도로 효율적인 작업 가능

In [149]:
#0 부터 시작해서 10000000만개의 요소 가진 배열 생성
x=np.arange(10000000)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [152]:
%%time
#해당 셀의 동작 완료 소요시간을 알려주는 주피터명령어
#최상단(주석도 있으면 안됨)에 위치해야함
#반복문을 통한 합계
#시간 단위 : 1s=1,000ms ->1000000us
loop_result=0
for i in x:
    loop_result+=i
loop_result

D:\asw\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in long_scalars
  import sys


Wall time: 1.68 s


-2014260032

In [161]:
%%time
#x의 총합 넘파이로 구하기
np.sum(x)


Wall time: 7.98 ms


-2014260032